### PR TITLE
Fix IndexOutOfBoundsException when try to map inner hits with no results returned

### LINKED ISSUE #1997: IndexOutOfBoundsException when try to map inner hits with no results returned
Configuring `inner_hits` with a size of 0 will result in an `IndexOutOfBoundsException` when mapping inner hits.

```
WARN  o.s.d.e.core.SearchHitMapping - Could not map inner_hits
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.springframework.data.elasticsearch.core.SearchHitsImpl.getSearchHit(SearchHitsImpl.java:97)
	at org.springframework.data.elasticsearch.core.SearchHitMapping.mapInnerDocuments(SearchHitMapping.java:181)
	at org.springframework.data.elasticsearch.core.SearchHitMapping.mapInnerHits(SearchHitMapping.java:158)
	at org.springframework.data.elasticsearch.core.SearchHitMapping.mapHit(SearchHitMapping.java:115)
	at org.springframework.data.elasticsearch.core.SearchHitMapping.mapHitsFromResponse(SearchHitMapping.java:95)
	at org.springframework.data.elasticsearch.core.SearchHitMapping.mapHits(SearchHitMapping.java:71)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate$ReadSearchDocumentResponseCallback.doWith(AbstractElasticsearchTemplate.java:875)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate$ReadSearchDocumentResponseCallback.doWith(AbstractElasticsearchTemplate.java:860)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.search(ElasticsearchRestTemplate.java:299)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.search(AbstractElasticsearchTemplate.java:513)
	at ch.x28.jobportal.core.searchindex.SearchIndexRepositoryImpl.findAll(SearchIndexRepositoryImpl.java:56)
```

### PR DESCRIPTION
**Pull request by xhaggi**
Fixes #1997 

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] **There is a ticket in the bug tracker for the project in our [issue tracker](https://github.
  com/spring-projects/spring-data-elasticsearch/issues)**. Add the issue number to the _Closes #issue-number_ line below
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

Closes #issue-number

### CODE REVIEW

File: src/main/java/org/springframework/data/elasticsearch/core/SearchHitMapping.java [hunk 1]
```diff
@@ -194,7 +195,7 @@ public void mapHitsInCompletionSuggestion(@Nullable Suggest suggest) {
 	 */
 	private SearchHits<?> mapInnerDocuments(SearchHits<SearchDocument> searchHits, Class<T> type) {
 
-		if (searchHits.getTotalHits() == 0) {
+		if (searchHits.isEmpty()) {
```
Comment (sothawo) [inline src/main/java/org/springframework/data/elasticsearch/core/SearchHitMapping.java:198]: Do you have a test case showing the error with the old code? `SearchHits.getTotalHits()` returns a primitive `long` value. How does this produce an `IndexOutOfBoundsException`? It might be a `NaN` but then we should rather fix the setting of the `totalHits`property.

**Review by sothawo — CHANGES_REQUESTED** [review]

File: src/main/java/org/springframework/data/elasticsearch/core/SearchHitMapping.java (hunk 1 above)
Comment (xhaggi) [reply src/main/java/org/springframework/data/elasticsearch/core/SearchHitMapping.java:198]: The `IndexOutOfBoundsException` is thrown in line 203 when accessing `searchHits.getSearchHit(0)`. You can tell Elastic not to return inner hits by setting the `size` in `inner_hits` to 0. This way you can keep track of total hits without returning any results.

Comment (xhaggi) [reply src/main/java/org/springframework/data/elasticsearch/core/SearchHitMapping.java:198]: By the way, it's not so easy to add a test case for this, because the exceptions are caught here and only a warning is logged. I am not sure if we should change that as well.

Comment (sothawo) [reply src/main/java/org/springframework/data/elasticsearch/core/SearchHitMapping.java:198]: ok for the change. 

The exception should probably not be swallowed, it rather should be wrapped in a `UncategorizedElasticsearchException`.

As for the test: this could be done with a method in `org.springframework.data.elasticsearch.core.ElasticsearchTemplateTests`, insert a document, then do a search with the `inner_hits` set to zero which should then produce the exception with the old code.

Comment (AntonLGVS) [reply src/main/java/org/springframework/data/elasticsearch/core/SearchHitMapping.java:198]: **searchHits.getTotalHits() == searchHits.getSearchHits().size()** ?
**_searchHits.getTotalHits()_** - number of found.
**_searchHits.getSearchHits()_** - number of received for current page.
They may not be equal. Or am I wrong?

maybe: 
```
if (!searchHits.hasSearchHits()) {
```

and **searchHits.getSearchHit(0)** not throw _IndexOutOfBoundsException_

Comment (xhaggi) [reply src/main/java/org/springframework/data/elasticsearch/core/SearchHitMapping.java:199]: @sothawo everything has now been addressed and force-pushed.

**Comment by xhaggi** [comment]
@sothawo a backport to 4.2 and 4.3 would be great to get rid of the warning. Let me know if you want me to do that.
