### PR TITLE
Expose search shard statistics in search hits

### LINKED ISSUE #2605: Expose the method to get total shards & successful shards from SearchHits response
Hi Team,

We have one use case where we have to check and need to do some handling on the basis of total shards and successful shards. So it will be good if we can expose them from org.springframework.data.elasticsearch.core.SearchHits

`/*
public interface SearchHits<T> extends Streamable<SearchHit<T>> {

	/**
	 * @return the aggregations.
	 */
	@Nullable
	AggregationsContainer<?> getAggregations();

	/**
	 * @return the maximum score
	 */
	float getMaxScore();

	/**
	 * @param index position in List.
	 * @return the {@link SearchHit} at position {index}
	 * @throws IndexOutOfBoundsException on invalid index
	 */
	SearchHit<T> getSearchHit(int index);

	/**
	 * @return the contained {@link SearchHit}s.
	 */
	List<SearchHit<T>> getSearchHits();

	/**
	 * @return the number of total hits.
	 */
	long getTotalHits();

	/**
	 * @return the relation for the total hits
	 */
	TotalHitsRelation getTotalHitsRelation();

	/**
	 * @return true if aggregations are available
	 */
	default boolean hasAggregations() {
		return getAggregations() != null;
	}

	/**
	 * @return whether the {@link SearchHits} has search hits.
	 */
	default boolean hasSearchHits() {
		return !getSearchHits().isEmpty();
	}

	/**
	 * @return the suggest response
	 * @since 4.3
	 */
	@Nullable
	Suggest getSuggest();

	/**
	 * @return wether the {@link SearchHits} has a suggest response.
	 * @since 4.3
	 */
	default boolean hasSuggest() {
		return getSuggest() != null;
	}

	/**
	 * @return an iterator for {@link SearchHit}
	 */
	default Iterator<SearchHit<T>> iterator() {
		return getSearchHits().iterator();
	}

}
`

### PR DESCRIPTION
**Pull request by puppylpg**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] **There is a ticket in the bug tracker for the project in our [issue tracker](https://github.com/spring-projects/spring-data-elasticsearch/issues)**. Add the issue number to the _Closes #issue-number_ line below
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

Closes #2605

### CODE REVIEW

File: src/main/java/org/springframework/data/elasticsearch/core/SearchShardStatistics.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+ * limitations under the License.
+ */
+package org.springframework.data.elasticsearch.core;
+
+import org.springframework.lang.Nullable;
+
+/**
+ * @author Haibo Liu
+ */
+public record SearchShardStatistics(Number failed, Number successful, Number total, @Nullable Number skipped) {
```
Comment (sothawo) [inline src/main/java/org/springframework/data/elasticsearch/core/SearchShardStatistics.java:23]: wouldn't it make sense to add the list of ShardFailures as well?

File: src/main/java/org/springframework/data/elasticsearch/repository/query/AbstractElasticsearchRepositoryQuery.java [hunk 2]
```diff
@@ -110,13 +107,7 @@ public Object execute(Object[] parameters) {
...
 			if (parameterAccessor.getPageable().isUnpaged()) {
 				int itemCount = (int) elasticsearchOperations.count(query, clazz, index);
-
-				if (itemCount == 0) {
-					result = new SearchHitsImpl<>(0, TotalHitsRelation.EQUAL_TO, Float.NaN, null,
-							query.getPointInTime() != null ? query.getPointInTime().id() : null, Collections.emptyList(), null, null);
-				} else {
-					query.setPageable(PageRequest.of(0, Math.max(1, itemCount)));
-				}
+				query.setPageable(PageRequest.of(0, Math.max(1, itemCount)));
```
Comment (sothawo) [inline src/main/java/org/springframework/data/elasticsearch/repository/query/AbstractElasticsearchRepositoryQuery.java:110]: in line 115 result now is always null, so the if condition can be removed

File: src/test/java/org/springframework/data/elasticsearch/client/elc/SearchDocumentResponseBuilderUnitTests.java [hunk 3]
```diff
@@ -108,4 +112,32 @@ void shouldGetPhraseSuggestion() throws JSONException {
...
+				.hits(new ArrayList<>())
+				.build();
+
+		ShardStatistics shards = new ShardStatistics.Builder()
+				.total(15)
+				.successful(15)
+				.skipped(0)
+				.failed(0)
+				.build();
+
```
Comment (sothawo) [inline src/test/java/org/springframework/data/elasticsearch/client/elc/SearchDocumentResponseBuilderUnitTests.java:132]: add failure objects

**Review by sothawo — CHANGES_REQUESTED** [review]
Thank you for implementing this. Please add the failure objects to the new class, otherwise just some minor comments.

File: src/main/java/org/springframework/data/elasticsearch/core/SearchShardStatistics.java (hunk 1 above)
Comment (puppylpg) [reply src/main/java/org/springframework/data/elasticsearch/core/SearchShardStatistics.java:23]: I found this a little awkward: if `ShardFailure` is added into this class, shall we rewrite `ShardFailure`(and `ErrorCause`, `JsonData map` inside it) of our own? or shall we just expose these classes written by `elasticsearch-java` to our users?

I think spring-data-elasticsearch obeys the first rule and almost all the classes exposed to the users are written by spring-data-elasticsearch itself. However, I also notice that when querying aggregations, the class `co.elastic.clients.elasticsearch._types.aggregations.Aggregate` in `elasticsearch-java` is exposed to the users directly.

So which implementation should we choose?

Comment (sothawo) [reply src/main/java/org/springframework/data/elasticsearch/core/SearchShardStatistics.java:23]: It's awkward, yes. And there are already places where Elasticsearch failures are mapped to corresponding classes from Spring Data Elasticsearch. The ugly thing is, that the Elasticsearch client library for this parts  is autogenerated from a schema definition, but this generation is not able to reuse classes, so they redefine them multiple times.

As for exposing Elasticsearch classes: No, we cannot do that, because not every user is using Elasticsearch. Spring Data Elasticsearch also is the base project for [spring-data-opensearch](https://github.com/opensearch-project/spring-data-opensearch) where basically the low level implementation is changed, but the high level stuff is used from Spring Data Elasticsearch. And we cannot introduce Elasticsearch classes into that code.

In version 4, we had Elasticsearch classes happily over the codebase, but with the refactoring needed for the new client in 5 all the code dependent on the old classes went into the `.erhlc.` package and the new one to `.elc.`. There first was the idea of eventually adding a `.orhlc.` for the opensearch rest high level client, but after a call with people from AWS it was decided that all the client specific code has to go into a separate package, they provide the opensearch part in their own project. And everything outside of this pacakge must be independent of a client library.

As for the aggregations: In the Spring Data Elasticsearch code, only interfaces are returned, the concrete implementations come from the client implementations. The main reason why there is no client independent mapping for aggregations is the shere amount of classes that would be needed to map, the last time I checked there were almost 190 classes in the Elasticsearch package. And that needs to be done in every client implementation.

Comment (puppylpg) [reply src/main/java/org/springframework/data/elasticsearch/core/SearchShardStatistics.java:23]: Thanks for the detailed explanation. I've seen the corresponding parts, and luckily at least the error cause is reused in the elasticsearch client schema definition :smiling_face_with_tear:
